# docker version
version: "3"

services:  

  go_svr:
    build: .
    ports:
      - "8888:8888"
    depends_on:
      keycloak_svr:
        condition: service_healthy

  postgres_svr: 
    image: postgres
    command: postgres -c 'max_connections=200' && postgres -c 'shared_buffers=24MB'    
    environment:
      # Environment Variables expecially for Postgres
      POSTGRES_DB: db_name
      POSTGRES_USER: user_name
      POSTGRES_PASSWORD: password
    healthcheck:
      test: "exit 0"
    ports:
      - "5432:5432"

  keycloak_svr:    
    image: quay.io/keycloak/keycloak:21.0.2        
    command: start-dev
    environment:      
      KC_DB: postgres
      KC_DB_URL_HOST: postgres_svr
      KC_DB_URL_DATABASE: db_name
      KC_DB_PASSWORD: password
      KC_DB_USERNAME: user_name
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    healthcheck:
      test: "exit 0"   
    ports:
      - "8080:8080"       
    depends_on:      
      postgres_svr:
        condition: service_healthy

